channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::statsmodels=0.14.2
  - conda-forge::scanpy=1.10.2
  - conda-forge::scipy=1.14.1
  - conda-forge::pandas=2.2.2
  - conda-forge::seaborn=0.13.2
  - conda-forge::anndata=0.10.3
  - conda-forge::python-igraph=0.11.6
  - conda-forge::numpy=1.26.4
  - conda-forge::matplotlib=3.9.1
